baseURL = "http://opsgeektech.netlify.app"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "OpsGeek"
[markup.goldmark.renderer]
unsafe = true
